export const ACTION_TYPES = {
  MACHINE_TRANSLATION: "MACHINE_TRANSLATION",
  OCR: "OCR",
  IF_ELSE: "IF_ELSE",
};

export const TRIGGER_TYPES = {
  RECORD_CREATED: "RECORD_CREATED",
  RECORD_UPDATED: "RECORD_UPDATED",
};

export const NODE_TYPES = {
  TRIGGER: "TRIGGER",
  ACTION: "ACTION",
  ADD_ICON: "ADD_ICON",
  ADD_ACTION: "ADD_ACTION",
};
